### ISSUE TITLE
Tests are wrong

### ISSUE THREAD

**Issue by charaton** [charaton/blog#3]
Database doesn't seem to be clearing after tests, so uniqueness validations sometimes fail.

```ruby
Failures:

  1) PostsController showing index of all posts assigns all posts to the @posts instance variable
     Failure/Error: before(:context) { create_list(:post, 2) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Title has already been taken
     # ./spec/controllers/posts_controller_spec.rb:5:in `block (3 levels) in <top (required)>'

  2) PostsController showing index of all posts renders the index template
     Failure/Error: before(:context) { create_list(:post, 2) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Title has already been taken
     # ./spec/controllers/posts_controller_spec.rb:5:in `block (3 levels) in <top (required)>'

Finished in 2.74 seconds (files took 2.01 seconds to load)
46 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/controllers/posts_controller_spec.rb:8 # PostsController showing index of all posts assigns all posts to the @posts instance variable
rspec ./spec/controllers/posts_controller_spec.rb:12 # PostsController showing index of all posts renders the index template
```

**Comment by charaton** [comment]
Fixed in commit 778a9456593ffcb8d89656d86c9c8a785e6351e6
